### ISSUE TITLE
Is the scraper meant to take days to do its work?

### ISSUE THREAD

**Issue by hannahlindsley** [fcappdev/OpenAgClassifier#21]
I've rewritten to use selenium, pandas, etc, but I can't tell if I've done it correctly. It looks from my first few rounds like it will take days to collect all of the data, and I don't see any parallelization. Have I just implemented something incorrectly, or is it actually supposed to take that long?

**Comment by brainsqueeze** [comment]
Yes, it was intentionally designed this way.  It is hitting a public search API provided by the Food and Agriculture Organization of the United Nations which is powering their search page.  To avoid over burdening their endpoint (which had experienced intermittent down time while we were collecting data) we intentionally did not parallelize this scraper.  It also sleeps periodically, again, to avoid putting undue stress on their server.  This was deemed the best collection of publicly available text documents coded to the AGROVOC taxonomy.

If you are interested only in the same subset of the taxonomy as in this project then I would like to add a reminder that the trained models are available [here](https://s3.amazonaws.com/fc-public/svm/open_ag_models.zip).

**Comment by hannahlindsley** [comment]
Ah, ok, gotcha. I wanted to try out a couple of different models on the dataset, so I'll just let it run for awhile :) Thanks for the super fast response.

**Comment by brainsqueeze** [comment]
No problem, happy to help!
